# Generated by Django 5.2.3 on 2025-06-18 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.PositiveIntegerField()),
                ("course", models.CharField(max_length=255)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("midterm", "Midterm"), ("final", "Final")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invigilators",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"user_type": "faculty"},
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.program"
                    ),
                ),
                ("rooms", models.ManyToManyField(blank=True, to="rooms.room")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.section"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
    ]
